services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - /var/influxdb/data:/var/lib/influxdb2
      - /var/influxdb/config:/etc/influxdb2
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin_influx
      - DOCKER_INFLUXDB_INIT_PASSWORD=L1Y:b@xA?@x6u1yCce'9
      - DOCKER_INFLUXDB_INIT_ORG=meine-wiese.de
      - DOCKER_INFLUXDB_INIT_BUCKET=traefik
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.influxdb.rule=Host(`influxdb.meine-wiese.de`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=leresolver"
      - "traefik.http.routers.influxdb.service=influxdb"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    networks:
      - traefik_proxy
      - databases
      - influx_grafana

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /var/docker/grafana/data:/var/lib/grafana:rw
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.grafana.rule=Host(`grafana.meine-wiese.de`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=leresolver"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy
      - databases
      - influx_grafana

networks:
  traefik_proxy:
    external: true
  databases:
    external: true
  influx_grafana:
    external: false
