apiVersion: v1
kind: Namespace
metadata:
  name: hello-world

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: argocd.meine-wiese.de   # Replace with your hostname
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
  tls:
  - hosts:
    - argocd.meine-wiese.de        # Replace with your hostname
    secretName: argocd-tls         # Optionally, set up a TLS certificate

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-env
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-env
  template:
    metadata:
      labels:
        app: hello-world-env
    spec:
      containers:
      - name: hello-world-env
        image: bithavoc/hello-world-env
        env:
        - name: MESSAGE
          value: "cool by env"
        ports:
        - containerPort: 3000
