apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-deployment
  namespace: argo-demo  # Specify your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
      - name: nginx-php
        image: manu-fuhrmann/nginx-php-own  # Replace with your Docker Hub image
        ports:
        - containerPort: 80
        volumeMounts:  # You can use this if you want to mount files at startup
        - name: html-storage
          mountPath: /var/www/html  # The default document root for nginx
      initContainers:
      - name: git-clone
        image: alpine/git  # Lightweight image to perform the clone
        command: ['sh', '-c', 'git clone --single-branch --branch main https://github.com/ManuFuhrmann/upload /var/www/html']  # Adjust this to clone directly to the nginx path
      volumes:  # Remove PVC references
      - name: html-storage
        emptyDir: {}  # Use emptyDir for temporary storage
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-php-service
  namespace: argo-demo  # Ensure the service is in the correct namespace
spec:
  type: NodePort  # Expose the service externally
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can specify a NodePort or let Kubernetes choose one
  selector:
    app: nginx-php
